name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restoring dependencies Application layer
      run: dotnet restore Application\Application.csproj
    - name: Build
      run: dotnet build Application\Application.csproj --no-restore
    - name: Test
      run: dotnet test Tests\Tests.csproj --no-build --verbosity normal
