name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restoring dependencies for the solution
      run: dotnet restore src/Rhynow.sln
    
    - name: Building Solution
      run: dotnet build src/Rhynow.sln --no-restore
    
    - name: Run Unit Tests
      run: dotnet test src/Rhynow.sln  --no-build --verbosity normal
    
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format

    # - name: Run dotnet format Application Layer
    #   run: dotnet format --check --verbosity diagnostic Application/Application.csproj
 